### ISSUE TITLE
Unable to start openassistant : Error loading sound: Parent module 'oa.modules' not loaded, cannot perform relative import

### ISSUE THREAD

**Issue by analyticsUser** [openassistant/oa-core#12]
Hi,
I have followed all the steps described on github, but I am unable to start open-assistant. Following is the error: 

[2019-04-16 16:11:24,762] INFO     MainThread [__main__.py:<module>:94]    Start Open Assistant
[2019-04-16 16:11:24,762] INFO     MainThread [__main__.py:__init__:18]    Initializing Open Assistant
[2019-04-16 16:11:24,762] DEBUG    MainThread [agent.py:__init__:13]    <__main__.OpenAssistant object at 0x7fd0bc6a3908>
[2019-04-16 16:11:24,762] INFO     MainThread [agent.py:_load_modules:33]    Loading Modules <- /home/user/Music/oa-core/oa/modules
[2019-04-16 16:11:24,762] INFO     MainThread [util.py:load_module:60]    sound <- /home/user/Music/oa-core/oa/modules/sound
[2019-04-16 16:11:24,762] ERROR    MainThread [agent.py:_load_modules:42]    Error loading sound: Parent module 'oa.modules' not loaded, cannot perform relative import
[2019-04-16 16:11:24,762] INFO     MainThread [util.py:load_module:60]    voice <- /home/user/Music/oa-core/oa/modules/voice
[2019-04-16 16:11:24,762] ERROR    MainThread [agent.py:_load_modules:42]    Error loading voice: Parent module 'oa.modules' not loaded, cannot perform relative import
[2019-04-16 16:11:24,762] INFO     MainThread [util.py:load_module:60]    speech_recognition <- /home/user/Music/oa-core/oa/modules/speech_recognition
[2019-04-16 16:11:24,762] ERROR    MainThread [agent.py:_load_modules:42]    Error loading speech_recognition: Parent module 'oa.modules' not loaded, cannot perform relative import
[2019-04-16 16:11:24,763] INFO     MainThread [util.py:load_module:60]    ear <- /home/user/Music/oa-core/oa/modules/ear
[2019-04-16 16:11:24,763] ERROR    MainThread [agent.py:_load_modules:42]    Error loading ear: Parent module 'oa.modules' not loaded, cannot perform relative import
[2019-04-16 16:11:24,763] INFO     MainThread [util.py:load_module:60]    mind <- /home/user/Music/oa-core/oa/modules/mind
[2019-04-16 16:11:24,763] ERROR    MainThread [agent.py:_load_modules:42]    Error loading mind: Parent module 'oa.modules' not loaded, cannot perform relative import
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/Music/oa-core/oa/__main__.py", line 96, in <module>
    start()
  File "/home/user/Music/oa-core/oa/__main__.py", line 44, in start
    a.parts['ear'].output += [a.parts.speech_recognition]
  File "/home/user/Music/oa-core/oa/core/util.py", line 89, in __getitem__
    return getattr(self, key)
AttributeError: 'Core' object has no attribute 'ear'

1. cd oa-core
2. python3 -m oa
4. Error as above

Desktop:
 - OS: Ubuntu 16.04
- Python version : Python 3.5

I am stuck on above step for too long. Kindly, help on the same.

**Comment by joshuashort** [comment]
Have you installed the python dependencies (`pip3 install -r requirements.txt`)?

**Comment by analyticsUser** [comment]
Yes, I followed the above steps and installed all dependencies as mentioned in README.md
My Python version is 3.5 and I used pip version 19.x .

Is there some discrepancy in **python** version and **pip** version to be used ?
Also, I ran command as **pip** install  -r requirements.txt instead of using **pip3**.

Any kind of help is much appreciated to get me started with **openassistant** as I am still stuck at the same step ( Parent module 'oa.modules' not loaded) . Thank you !!

**Comment by joshuashort** [comment]
Thanks for the patience :)

It’s hard to say for sure since people configure their systems in all kinds of ways..

Is your system’s native/built-in version of Python 2.x or 3.x? You can check by just running `python`, not `python3`. If it’s 2.x, then `pip` is going to also be for 2.x, so it would seem like you have the dependencies installed, but they’re actually installed for the wrong version of Python. Also, `pip3` might need to be installed separately.

Makes sense?

**Comment by jiachenwei** [comment]
Hello!
I also meet this trouble.
My env is base on anaconda python 3.6.2, and OS is Ubunut 18.04.

<pre>[2019-04-27 13:48:17,066] INFO     MainThread [__main__.py:&lt;module&gt;:94]    Start Open Assistant
[2019-04-27 13:48:17,066] INFO     MainThread [__main__.py:__init__:18]    Initializing Open Assistant
[2019-04-27 13:48:17,066] DEBUG    MainThread [agent.py:__init__:13]    &lt;__main__.OpenAssistant object at 0x7fef5aeb7cc0&gt;
[2019-04-27 13:48:17,066] INFO     MainThread [agent.py:_load_modules:33]    Loading Modules &lt;- /home/jia/Downloads/oa-core-master/oa/modules
[2019-04-27 13:48:17,066] INFO     MainThread [util.py:load_module:60]    sound &lt;- /home/jia/Downloads/oa-core-master/oa/modules/sound
[2019-04-27 13:48:17,066] ERROR    MainThread [agent.py:_load_modules:42]    Error loading sound: Parent module &apos;oa.modules&apos; not loaded, cannot perform relative import
[2019-04-27 13:48:17,067] INFO     MainThread [util.py:load_module:60]    voice &lt;- /home/jia/Downloads/oa-core-master/oa/modules/voice
[2019-04-27 13:48:17,067] ERROR    MainThread [agent.py:_load_modules:42]    Error loading voice: Parent module &apos;oa.modules&apos; not loaded, cannot perform relative import
[2019-04-27 13:48:17,067] INFO     MainThread [util.py:load_module:60]    speech_recognition &lt;- /home/jia/Downloads/oa-core-master/oa/modules/speech_recognition
[2019-04-27 13:48:17,067] ERROR    MainThread [agent.py:_load_modules:42]    Error loading speech_recognition: Parent module &apos;oa.modules&apos; not loaded, cannot perform relative import
[2019-04-27 13:48:17,067] INFO     MainThread [util.py:load_module:60]    ear &lt;- /home/jia/Downloads/oa-core-master/oa/modules/ear
[2019-04-27 13:48:17,067] ERROR    MainThread [agent.py:_load_modules:42]    Error loading ear: Parent module &apos;oa.modules&apos; not loaded, cannot perform relative import
[2019-04-27 13:48:17,067] INFO     MainThread [util.py:load_module:60]    mind &lt;- /home/jia/Downloads/oa-core-master/oa/modules/mind
[2019-04-27 13:48:17,067] ERROR    MainThread [agent.py:_load_modules:42]    Error loading mind: Parent module &apos;oa.modules&apos; not loaded, cannot perform relative import
Traceback (most recent call last):
  File &quot;/home/jia/anaconda3/envs/oa/lib/python3.6/runpy.py&quot;, line 193, in _run_module_as_main
    &quot;__main__&quot;, mod_spec)
  File &quot;/home/jia/anaconda3/envs/oa/lib/python3.6/runpy.py&quot;, line 85, in _run_code
    exec(code, run_globals)
  File &quot;/home/jia/Downloads/oa-core-master/oa/__main__.py&quot;, line 96, in &lt;module&gt;
    start()
  File &quot;/home/jia/Downloads/oa-core-master/oa/__main__.py&quot;, line 44, in start
    a.parts[&apos;ear&apos;].output += [a.parts.speech_recognition]
  File &quot;/home/jia/Downloads/oa-core-master/oa/core/util.py&quot;, line 89, in __getitem__
    return getattr(self, key)
AttributeError: &apos;Core&apos; object has no attribute &apos;ear&apos;
</pre>

**Comment by xiaodongliu-nudt** [comment]
Stuck here too. My env is Ubuntu 16.04 and Python 3.5. Any help?? 
P.S. 'pip3 install -r requirements.txt' is finished in my env.

**Comment by jgrueb** [comment]
Same behaviour on Debian 9.9, Python 3.5.3 and correctly installed dependencies.

**Comment by joshuashort** [comment]
Merge #14 (thanks @jgrueb) should make things work in `master`..

@analyticsUser @JiaChenwei @xiaodongliu-fighting : does this resolve the issue?

**Comment by joshuashort** [comment]
I probably missed something obvious, but I found some old code with a comment about this issue.. I think the merged solution is better than the workaround (i.e. hard-coding an import of the base namespace).
